### ISSUE TITLE
Uncaught SyntaxError: ambiguous indirect export: default

### ISSUE THREAD

**Issue by ThaDaVos** [NathanAP/vue-google-maps-community-fork#10]
**Describe what you're reporting**
After installing the package, adding it to my `app.ts` by importing and `app.use` I am getting the error `Uncaught SyntaxError: ambiguous indirect export: default` in my console and the application does not load - if I remove the `app.use` the error goes away but of course I cannot use the package then.

**How can we reproduce it?**
Show us how to reproduce the bug.

Example:

1. NPM install the package
2. Add it to your `app.ts` the way it's shown in the docs
3. See error

**What were your expecting to happen?**
A description of the expected behavior.
No error, able to use the components

**What happened?**
A description of the actual behavior.
Got an error

**Screenshots**
You can send screenshots to help express what you want to show us.

**Device or enviroment**

- In which OS are you seeing this bug? Examples: Windows 11, Ubuntu, iOS.
- If it is relevant, what browser are you? Examples: Chrome, Safari, Opera.
- What is your npm version? You can check using npm -v. `8.15.0`
- What is your vue version? You can check using npm list. `3.2.40`
- What is your vue-google-maps-community-fork version? You can check using npm list. `0.1.4`
- Builder used: Vite, version: 3.1.8

**Additional context**
You also can add more context for your situation here. Feel free to express whatever you think its important.

**Comment by ThaDaVos** [comment]
It seems to be related to:
```javascript
import equal from '/node_modules/fast-deep-equal/index.js?v=290a8b6e';
```

**Comment by ThaDaVos** [comment]
So it seems related to: https://github.com/NathanAP/vue-google-maps-community-fork/issues/4

**Comment by NathanAP** [comment]
It seems that their exports are broken with `fast-deep-equal` ):
I believe you're following our guide to configure your `main`, so I believe you made everything right.

- Is Fawmi's version working for you?
- Are you on Vite? Did you try that hack to add `fast-deep-equal` to `optimizeDeps`?

**Comment by ThaDaVos** [comment]
I used the hack to make it work as I am using `vite`

**Comment by NathanAP** [comment]
I will close this as it really seems related to #4 . If this still ocurring later we will reopen it.
