### ISSUE TITLE
Nuxt3 Production Fix

### ISSUE THREAD

**Issue by vaniaalex** [NathanAP/vue-google-maps-community-fork#14]
Hello, 

So I've tested on the nuxt3 website this module.

In the development environment the instruction you have right now in Readme works well, but when you try to build or generate the project it gives an error for import from @googlemaps/markerckuster.

In order to fix that you need to add another module in transpile array to look like this
`build: {
    transpile: [
      "vue-google-maps-community-fork",
      "@googlemaps/markerclusterer",
    ],
  },`

Here is the link for the Nuxt3 docs, where it explains why

[https://v3.nuxtjs.org/guide/concepts/esm/#transpiling-libraries](Nuxt3 Docs Transpile Libraries)

Hope you update the Readme file.
Thanks!

**Comment by NathanAP** [comment]
Hello! Thank you so much for pointing it out.

I just updated the Readme file, can you check if it is correct?
I will update the docs as well as soon as I can.

**Comment by vaniaalex** [comment]
Looks great!
