### ISSUE TITLE
When using  <GMapCluster > bug

### ISSUE THREAD

**Issue by metinjakupi** [NathanAP/vue-google-maps-community-fork#25]
Hello im using GMapCluster and when i click somewhere in the map my markers are gone and im getting this error

supercluster.ts:66 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lng')
    at supercluster.ts:66:35
    at Array.map (<anonymous>)
    at SuperClusterAlgorithm.calculate (supercluster.ts:60:35)
    at MarkerClusterer.render (markerclusterer.ts:173:52)
    at MarkerClusterer.addMarker (markerclusterer.ts:105:12)
    at marker.vue:123:12

**Comment by NathanAP** [comment]
Hello! Thanks for reporting

I'm not sure what might be causing it, maybe you could try to reproduce it in Playcode.

The `marker.vue:123:12` is refered to this part of the code:

![image](https://user-images.githubusercontent.com/12821171/205903879-98081eca-356d-4f60-8a54-6b346c91acd0.png)

but that `addMarker` function doensn't seem to be ours...

**Comment by NathanAP** [comment]
I'm closing it until we get more info about this. You are free to add content to this conversation.

**Comment by metinjakupi** [comment]
Sorry, i fixed it somehow it added blank markers without lat&lng
