### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by AubSs** [NathanAP/vue-google-maps-community-fork#30]
Hello,

there is a problem related to this package and this [vue issue](https://github.com/vuejs/core/issues/4344)

`TypeError: Cannot read properties of null (reading 'isCE')`

Any idea why when I import this package it throw this ?

More info, the problem is only with Vite4, it work fine with vite3

Thanks!

```vue
<template>
    <el-card v-if="address" shadow="hover" :body-style="{ padding: 0, height: '100%', width: '100%' }">
        <GMapMap :center="position" :zoom="17" class="h-full w-full"
                 :options="{
                     zoomControl: false, mapTypeControl: false, scaleControl: false, streetViewControl: false, rotateControl: false, fullscreenControl: false,
                     styles: [ { featureType: 'poi', stylers: [ { visibility: 'off' } ] } ]
                 }"
        >
            <GMapMarker :position="position" :icon="{ url: '/logo/logo-pin-color.svg', scaledSize: { width: 35, height: 35 } }" />
        </GMapMap>
    </el-card>
</template>

<script setup lang="ts">
import { IAddress } from '@common/models';
import { computed } from 'vue';

const props = defineProps<{ address: IAddress }>();

const position = computed(() => ({
    lat: parseFloat(`${props.address?.position[1] || 0}`),
    lng: parseFloat(`${props.address?.position[0] || 0}`),
}));
</script>
```

**Comment by websitevirtuoso** [comment]
Do you use vite 4?

**Comment by websitevirtuoso** [comment]
I can confirm the bug. Checking why this happens and working on PR. If you can figure out faster please create PR

**Comment by websitevirtuoso** [comment]
I have no idea why this happens when using Vite4. I have the same issue. Tmp had to rollback to vite3.
The problem with plugin, the code is not clear for me. Hope somebody can help with this bug.

**Comment by NathanAP** [comment]
Hello! Sorry being late on this issue.

Did you guys tried [this](https://github.com/amirkian007/vue-awesome-sidebar/issues/2#issuecomment-1314582782) ?

**Comment by NathanAP** [comment]
I updated the project that I use our package to vite 4.0.2, its working fine, maybe its something more specific? I can create simple maps and markers.

**Comment by AubSs** [comment]
Sorry for the late response.

Yeah it seems that only vite 4.0.1 is causing this.
Upgrading to  4.0.1 resolve everything.

Closing this issue now :)

**Comment by NathanAP** [comment]
Great, thats awesome! Thanks for reporting :)
