### ISSUE TITLE
Missing "emits" and propagation of events in circle and rectangle

### ISSUE THREAD

**Issue by oliverkirsch** [NathanAP/vue-google-maps-community-fork#53]
Hi everyone,
further "playing" with this project, I stumbled upon a warning regarding a missing "emits" for the _circle_ component. When adding this option for a test, it lacked propagation.

As far as I could see this issue also affects the _rectangle_ component.

If I understood everything correctly, adding `emits: events` to the export and using the afterCreate hook used in other components to register and actively emit events should do the trick, see here:
https://github.com/NathanAP/vue-google-maps-community-fork/commit/1e1222f8d0085576043c5aeb93a058e7532db763

Thanks for looking into this!

**Comment by NathanAP** [comment]
Hello! Thanks for your help!

Can you add this to a PR? It will be easier for people help you improve and test it :)

You need to create a new branch inside the project, make your commits and then open a PR.

**Comment by NathanAP** [comment]
#54 is now merged, so I'm closing this one :) Let me know if there is something else related to this and I'll open again
