### ISSUE TITLE
(Question) How to show the marker in my map after picking a place in autocomplete

### ISSUE THREAD

**Issue by alchemi009** [NathanAP/vue-google-maps-community-fork#56]
How can I achieve this after selecting a place (text input) in autocomplete component I want to display it to my map and show also the marker on it

here is my code

![image](https://i.ibb.co/1fbJvF0/1.png)

and this is my function
![image](https://user-images.githubusercontent.com/49689634/221351036-8ba1111b-8bc3-4746-bb6a-80057c1a0bdb.png)

I tried several times it took 3 days but still no progress hope someone can help me thanks!

**Comment by NathanAP** [comment]
Hello! Did you try to use [these](https://vue-google-maps-community-fork.netlify.app/components/marker.html) examples as base? Also, are you being able to show markers on your map? Because after that, all you need to do is to change the values of them and everything works fine :)

**Comment by alchemi009** [comment]
> Hello! Did you try to use [these](https://vue-google-maps-community-fork.netlify.app/components/marker.html) examples as base? Also, are you being able to show markers on your map? Because after that, all you need to do is to change the values of them and everything works fine :)

Yes It show on my map :D

![image](https://user-images.githubusercontent.com/49689634/221361690-f43377b0-85e4-4b4c-92f5-ac75381d640c.png)

heres my updated code 

```
const markers = ref([{
  position: {
    lat: 14.5069174,
    lng: 121.0409052,
  }
}])
```

```
<GMapMarker
  :key="index"
  v-for="(m, index) in markers"
  :position="m.position"
  :clickable="true"
  :draggable="true"
/>
```

```
<!-- Search -->
<GMapAutocomplete
   placeholder="Search Location"
   @place_changed="setPlace"
   :options="{
   componentRestrictions: { country: `ph` },
   fields: [`address_components`, `geometry`],
   types: [`establishment`],
   }"
>
</GMapAutocomplete>
```

My Real Concern was If  I pick a place in autocomplete I want to show the marker on my map 
![image](https://user-images.githubusercontent.com/49689634/221361807-49d37ba5-13ff-4723-81f5-4315db7a691a.png)

Still cant find how to show it I hope you understand what I mean hahaha thanks!

**Comment by alchemi009** [comment]
I got it now :D 

heres what I added
```
<script setup>
import { ref, onMounted } from 'vue';

const center = ref({
       lat: 14.5069174,
       lng: 121.0409052,
});

const markers = ref([{
  position: {
    lat: 14.5069174,
    lng: 121.0409052,
  },
}])

const place = ref({});

function setPlace(place) {
  
  markerSelected.value = {
    lat: place.geometry.location.lat(),
    lng: place.geometry.location.lng(),
  }

  navigator.geolocation.getCurrentPosition(position => {
    center.value = {
      lat: place.geometry.location.lat(),
        lng: place.geometry.location.lng(),
    };
  });

    markers.value = [
    {
      position: {
        lat: place.geometry.location.lat(),
        lng: place.geometry.location.lng(),
        }
    },
      ];
}

onMounted(() => {
  setPlace(place);
})

</script>
```

and in my autocomplete and markers base still the same

**Comment by NathanAP** [comment]
I'm glad you handle it! 

Let me know if I can help you about this again!

**Comment by alchemi009** [comment]
Sure!  I will, haha thanks!
