### ISSUE TITLE
The requested module 'fast-deep-equal' does not provide an export named 'default' (at index.esm.js?v=c805bd14:1:8)

### ISSUE THREAD

**Issue by Viktohblake** [NathanAP/vue-google-maps-community-fork#65]
I am getting this error and I believe it has something to do with this package. Everything prior to this time was working but when I did some work on google maps nearby search and pushed to github, a collaborator of mine did a pull from the project and is getting this error. But on my end I don't have that error. I tried a fresh clone of the project from github to my PC and I also did get the error. I think it has something to do with maybe a recent update made on this package.

Uncaught SyntaxError: The requested module '/_nuxt/node_modules/fast-deep-equal/index.js?v=c805bd14' does not provide an export named 'default' (at index.esm.js?v=c805bd14:1:8)

import equal from '/_nuxt/node_modules/fast-deep-equal/index.js?v=c805bd14';

**Comment by NathanAP** [comment]
https://github.com/NathanAP/vue-google-maps-community-fork/issues/4
