### ISSUE TITLE
Custom marker fill color

### ISSUE THREAD

**Issue by Julius-Bendt** [NathanAP/vue-google-maps-community-fork#67]
**Describe what you're reporting**
I'm trying to set a fill color, for a custom svg marker

**How can we reproduce it?**
copy and paste the following code (or, just try to set a custom marker)

```vue
  <GMapMap :center="{ lat: 57, lng: 5 }" :zoom="12" style="width:100% height:100%">
    <GMapCluster>
      <GMapMarker
        :icon="{
          fillColor: '#6366f1', // These dont work - with or without '#'
          strokeColor: '#6366f1',
          fill: '#6366f1',

          url: 'src/assets/svg/company.svg', // Make sure a svg is at this location
          scaledSize: { width: 32, height: 32 },
          labelOrigin: { x: 0, y: 0 }
        }"
        :position="{ lat: 57, lng: 5 }"
      >
      </GMapMarker>
    </GMapCluster>
  </GMapMap>
```

**What were your expecting to happen?**
I expected the fill color to be purple (#6366f1)

**What happened?**
The fill color is black/undefined

**Device or enviroment**
os: Windows 10,
browser: Chrome,
npm version: 9.3.0
vue version: 3.2.47
package version: 0.3.1

**Comment by andyslack** [comment]
Checkout this working example: https://github.com/NathanAP/vue-google-maps-community-fork/discussions/59#discussioncomment-5301541

If that does not help, let me know and I will provide more details.

**Comment by Julius-Bendt** [comment]
> Checkout this working example: [#59 (reply in thread)](https://github.com/NathanAP/vue-google-maps-community-fork/discussions/59#discussioncomment-5301541)
> 
> If that does not help, let me know and I will provide more details.

Sadly this didn't work. From what I can tell, you set the path instead of url, however, this causes both markers and clusters to disappear. 

Could you show how markerAircraft is imported?

**Comment by andyslack** [comment]
markerAircraft is a SVG path

```
export const markerAircraft =
	'M62 123c-2-2-3-6-4-11l-21 5-1-1v-5l1-2 18-13-1-27L3 79c-1 1-2 0-1-2l1-7 51-29-1-25c0-6 3-12 6-14 2-2 4-2 5 0 4 1 6 7 7 15l-1 24 51 29 1 7-2 2-51-10-1 27 19 13 1 2v5l-1 1-21-5c0 5-2 9-4 11z'
```

```
import { markerAircraft } from '@/assets/markers/aircraft'
```

**Comment by Julius-Bendt** [comment]
That did the trick! thanks a lot for the help!
